version: "3.9"

services:
        db:
                image: postgres
                restart: always
                hostname: eneo_db
                volumes:
                        - eneo-data:/var/lib/postgresql/data
                        - /home/ubuntu/eneo/priv/sql:/docker-entrypoint-initdb.d
                environment:
                        POSTGRES_PASSWORD: password
                        POSTGRES_USER: eneo
                        POSTGRES_DB: eneo
                deploy:
                        placement:
                                constraints: [node.hostname==piblue]
                ports:
                        - 5432:5432

volumes:
        eneo-data:
