version: "3.9"

services:
        eneo:
                image: bkopplin/eneo:latest
                environment:
                        PG_PASSWORD: password
                        PG_USER: eneo
                        PG_DATABASE: eneo
                        PG_HOST: eneo_db
                depends_on:
                        - db
                deploy:
                        mode: replicated
                        replicas: 3
                        #placement:
                                #constraints: [node.hostname==piblue]
                ports:
                        - "90:8080"
                command: ["foreground", ">>", "/tmp/eneo.log"]

        db:
                image: postgres
                restart: always
                hostname: eneo_db
                volumes:
                        - eneo-data:/var/lib/postgresql/data
                        - /home/ubuntu/eneo/priv/sql:/docker-entrypoint-initdb.d
                environment:
                        POSTGRES_PASSWORD: password
                        POSTGRES_USER: eneo
                        POSTGRES_DB: eneo
                deploy:
                        placement:
                                constraints: [node.hostname==piblue]
                ports:
                        - 5432:5432



volumes:
        eneo-data:
